### ISSUE TITLE
links to the spatstat page on CRAN don't work

### ISSUE THREAD

**Issue by kasselhingee** [spatstat/spatstat.github.io#1]
Links to www.cran.r-project.org/web/packages/spatstat/index.html aren't working for me.
Pasting this into my address bar seems to work instead:
 https://cran.r-project.org/web/packages/spatstat/index.html

I'm using Ubuntu Vivid. Error occurred with Firefox and Chromium

**Comment by rubak** [comment]
Thanks for spotting that. I will fix it right away.
